### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by aforren1** [aforren1/toon#9]
- [x] Interface to HAND (incl. reading on another thread/process)
- [x] Visual display of force in 3d space
- [ ] Control flow (e.g. "start acquiring data on space press") (see https://github.com/pytransitions/transitions for state machine)
- [ ] Data format (trial-by-trial & HDF5)

**Comment by aforren1** [comment]
Probably doesn't belong here anymore.
